teams:
  - name: QA Chapter
    slack_channel: "#team-chapter-qa"
    repositories:
      - e2e-tests
      - e2e-apps
      - test-precondition
    members:
      - davidmateodev
      - christopherlingcarragher
      - AnatoliTsoi
      - volodimirchernov